### ISSUE TITLE
Add install_requires=['cocotb'] to setup.py?

### ISSUE THREAD

**Issue by cmarqu** [wallento/cocotbext-uart#2]
Should the ``setup.py`` file get a line like ``install_requires=['cocotb']``, or would that prevent some use case I do not see?
(If this line was there, this repo would also be shown in Github's new "Used by" thingy next to "Watch" for cocotb.)

**Comment by wallento** [comment]
Oh, yes, it should be added!

**Comment by wallento** [comment]
Thanks. Do you think those are reasonable starting points to move the fifointerface and the uart into the cocotb github namespace? Also @imphil?

**Comment by cmarqu** [comment]
The general discussion (nothing much yet) about this is at https://github.com/cocotb/cocotb/issues/1008

**Comment by cmarqu** [comment]
https://github.com/cocotb/cocotb/network/dependents - it worked! :)

**Comment by wallento** [comment]
Nice, I love it. Thanks!
