### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by Martoni** [wallento/cocotbext-uart#4]
I'm trying to use this module as an example to write a [cocomod-spi](https://github.com/Martoni/cocomod-spi) module.
Have you got an example that use cocomod-uart ?

**Comment by wallento** [comment]
Hi,

sorry, I started this project and then got lost in other things. I hope I can get to it within the next two weeks. Thanks for your patience!

Best,
Stefan

**Comment by Martoni** [comment]
No problem ;)
I launched a discussion on a [guideline to write cocotb module](https://github.com/cocotb/cocotb/pull/1141). And yours seems to be the most advanced example.

**Comment by Martoni** [comment]
[Done :)](https://github.com/Martoni/cocotbext-uart/blob/master/README.rst)
